// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.11.4
// source: bookings.proto

package bookings

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Property struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DoorNumber string `protobuf:"bytes,2,opt,name=doorNumber,proto3" json:"doorNumber,omitempty"`
	Address    string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	City       string `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	Country    string `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *Property) Reset() {
	*x = Property{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bookings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_bookings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_bookings_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Property) GetDoorNumber() string {
	if x != nil {
		return x.DoorNumber
	}
	return ""
}

func (x *Property) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Property) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Property) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

var File_bookings_proto protoreflect.FileDescriptor

var file_bookings_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x82, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x6f, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x6f, 0x6f, 0x72, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x32, 0x43, 0x0a, 0x0b, 0x42, 0x6f,
	0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x41, 0x70, 0x69, 0x12, 0x34, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x0d, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x1a, 0x0d, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x0a, 0x5a, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_bookings_proto_rawDescOnce sync.Once
	file_bookings_proto_rawDescData = file_bookings_proto_rawDesc
)

func file_bookings_proto_rawDescGZIP() []byte {
	file_bookings_proto_rawDescOnce.Do(func() {
		file_bookings_proto_rawDescData = protoimpl.X.CompressGZIP(file_bookings_proto_rawDescData)
	})
	return file_bookings_proto_rawDescData
}

var file_bookings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bookings_proto_goTypes = []interface{}{
	(*Property)(nil), // 0: api.Property
}
var file_bookings_proto_depIdxs = []int32{
	0, // 0: api.BookingsApi.GetAllProperties:input_type -> api.Property
	0, // 1: api.BookingsApi.GetAllProperties:output_type -> api.Property
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bookings_proto_init() }
func file_bookings_proto_init() {
	if File_bookings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bookings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Property); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bookings_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bookings_proto_goTypes,
		DependencyIndexes: file_bookings_proto_depIdxs,
		MessageInfos:      file_bookings_proto_msgTypes,
	}.Build()
	File_bookings_proto = out.File
	file_bookings_proto_rawDesc = nil
	file_bookings_proto_goTypes = nil
	file_bookings_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookingsApiClient is the client API for BookingsApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingsApiClient interface {
	GetAllProperties(ctx context.Context, in *Property, opts ...grpc.CallOption) (BookingsApi_GetAllPropertiesClient, error)
}

type bookingsApiClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingsApiClient(cc grpc.ClientConnInterface) BookingsApiClient {
	return &bookingsApiClient{cc}
}

func (c *bookingsApiClient) GetAllProperties(ctx context.Context, in *Property, opts ...grpc.CallOption) (BookingsApi_GetAllPropertiesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BookingsApi_serviceDesc.Streams[0], "/api.BookingsApi/GetAllProperties", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookingsApiGetAllPropertiesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookingsApi_GetAllPropertiesClient interface {
	Recv() (*Property, error)
	grpc.ClientStream
}

type bookingsApiGetAllPropertiesClient struct {
	grpc.ClientStream
}

func (x *bookingsApiGetAllPropertiesClient) Recv() (*Property, error) {
	m := new(Property)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookingsApiServer is the server API for BookingsApi service.
type BookingsApiServer interface {
	GetAllProperties(*Property, BookingsApi_GetAllPropertiesServer) error
}

// UnimplementedBookingsApiServer can be embedded to have forward compatible implementations.
type UnimplementedBookingsApiServer struct {
}

func (*UnimplementedBookingsApiServer) GetAllProperties(*Property, BookingsApi_GetAllPropertiesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllProperties not implemented")
}

func RegisterBookingsApiServer(s *grpc.Server, srv BookingsApiServer) {
	s.RegisterService(&_BookingsApi_serviceDesc, srv)
}

func _BookingsApi_GetAllProperties_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Property)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookingsApiServer).GetAllProperties(m, &bookingsApiGetAllPropertiesServer{stream})
}

type BookingsApi_GetAllPropertiesServer interface {
	Send(*Property) error
	grpc.ServerStream
}

type bookingsApiGetAllPropertiesServer struct {
	grpc.ServerStream
}

func (x *bookingsApiGetAllPropertiesServer) Send(m *Property) error {
	return x.ServerStream.SendMsg(m)
}

var _BookingsApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.BookingsApi",
	HandlerType: (*BookingsApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllProperties",
			Handler:       _BookingsApi_GetAllProperties_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "bookings.proto",
}
