version: "3.7"
services:
  frontend:
    build:
        context: .
        dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"

  api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    entrypoint: ./wait-for.sh
    command: "db:5432 -- ./backend"
    depends_on:
      - db
    ports:
      - "8090:8090"

  migrate:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    entrypoint: ./wait-for.sh
    command: "db:5432 -- ./migrate -path=/migrations/ -database postgres://user:password@db:5432/bookings?sslmode=disable up"
    depends_on:
      - db

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookings